Global:
  device: gpu
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/rec/svtrv2_base666_ds_conv_local/
  eval_epoch_step: [0, 1]
  eval_batch_step: [0, 500]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  use_tensorboard: false
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path: &character_dict_path ./tools/utils/EN_symbol_dict.txt # 96en
  # ./tools/utils/ppocr_keys_v1.txt  # ch
  max_text_length: &max_text_length 25
  use_space_char: &use_space_char False
  save_res_path: ./output/rec/predicts_svtrv2.txt
  use_amp: True


Optimizer:
  name: AdamW
  lr: 0.00065 #4gpus bs256/gpu
  weight_decay: 0.05
  filter_bias_and_bn: True

LRScheduler:
  name: OneCycleLR
  # warmup_epoch: 2
  warmup_epoch: 1.5 # pct_start 0.075*20 = 1.5ep
  cycle_momentum: False

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
  Encoder:
    name: SVTRv2
    max_sz: [64, 640]
    use_pos_embed: False
    out_channels: 256
    dims: [128, 256, 384]
    depths: [6, 6, 6]
    num_heads: [4, 8, 12]
    mixer: [['Conv','Conv','Conv','Conv','Conv','Conv'],['Conv','Conv','Local','Local','Local','Local'],['Local','Local','Local','Local','Local','Local']]
    local_k: [[5, 5], [33, 29], [33, 29]]
    sub_k: [[1, 1], [2, 1], [-1, -1]]
    last_stage: True
  Decoder:
    name: CTCDecoder

Loss:
  name: CTCLoss
  zero_infinity: True

PostProcess:
  name: CTCLabelDecode
  character_dict_path: *character_dict_path
  use_space_char: *use_space_char

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: RatioDataSet
    ds_width: True
    max_ratio: &max_ratio 4
    min_ratio: 1
    base_shape: &base_shape [[64, 64], [96, 48], [112, 40], [128, 32]]
    base_h: &base_h 32
    padding: &padding False
    data_dir_list: ['../Union14M-LMDB-L-wh/train_challenging',
    '../Union14M-LMDB-L-wh/train_hard',
    '../Union14M-LMDB-L-wh/train_medium',
    '../Union14M-LMDB-L-wh/train_normal',
    '../Union14M-LMDB-L-wh/train_easy',
    ]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - PARSeqAug:
      - CTCLabelEncode: # Class handling label
          k: 8
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  sampler:
    name: RatioSampler
    scales: [[128, 32]] # w, h
    # divide_factor: to ensure the width and height dimensions can be devided by downsampling multiple
    first_bs: &bs 256
    fix_bs: false
    divided_factor: [4, 16] # w, h
    is_training: True
  loader:
    shuffle: True
    batch_size_per_card: *bs
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: RatioDataSet
    ds_width: True
    max_ratio: *max_ratio
    base_shape: *base_shape
    base_h: *base_h
    padding: *padding
    data_dir_list: ['../evaluation/CUTE80',
    '../evaluation/IC13_857',
    '../evaluation/IC15_1811',
    '../evaluation/IIIT5k_3000',
    '../evaluation/SVT',
    '../evaluation/SVTP']
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  sampler:
    name: RatioSampler
    scales: [[128, 32]] # w, h
    # divide_factor: to ensure the width and height dimensions can be devided by downsampling multiple
    first_bs: 256
    fix_bs: false
    divided_factor: [4, 16] # w, h
    is_training: False
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 4
