Global:
  device: gpu
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 100
  output_dir: ./output/rec/aster_tps_on
  eval_epoch_step: [0, 1]
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  use_tensorboard: false
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path:
  character_type: en
  max_text_length: 25
  use_space_char: False
  save_res_path: ./output/rec/predicts_aster_tps_on.txt


Optimizer:
  name: Adam
  lr: 0.001 # for 4gpus bs256/gpu
  weight_decay: 0.0
  filter_bias_and_bn: False
  betas: [0.9, 0.99]


LRScheduler:
  name: MultiStepLR
  milestones: [3,4]
  gamma: 0.1


Architecture:
  model_type: rec
  algorithm: aster
  Transform:
    name: Aster_TPS
  Encoder:
    name: ResNet_ASTER
  Decoder:
    name: ASTERDecoder

Loss:
  name: RobustScannerLoss
  # smoothing: True

Metric:
  name: RecMetric
  main_indicator: acc
  # is_filter: True

PostProcess:
  name: RobustScannerLabelDecode



Train:
  dataset:
    name: LMDBDataSet
    data_dir: ./
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RobustScannerLabelEncode: # Class handling label
      - SVTRResize:
          image_shape: [3, 32, 100]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'valid_ratio'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ./
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RobustScannerLabelEncode: # Class handling label
      - SVTRResize:
          image_shape: [3, 32, 100]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'valid_ratio'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 2
