Global:
  device: gpu
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/rec/robustscanner
  eval_epoch_step: [0, 1]
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  use_tensorboard: false
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path:
  character_type: en
  max_text_length: &max_text_length 25
  use_space_char: False
  save_res_path: ./output/rec/predicts_robustscanner.txt


Optimizer:
  name: Adam
  lr: 0.001 # for 4gpus bs256/gpu
  weight_decay: 0.0
  filter_bias_and_bn: False
  betas: [0.9, 0.99]


LRScheduler:
  name: MultiStepLR
  milestones: [3,4]
  gamma: 0.1

Architecture:
  model_type: rec
  algorithm: robustscanner
  in_channels: 3
  Transform:
  Encoder:
    name: ResNet31
    # init_type: KaimingNormal
  Decoder:
    name: RobustScannerHead
    enc_outchannles: 128
    hybrid_dec_rnn_layers: 2
    hybrid_dec_dropout: 0
    position_dec_rnn_layers: 2
    start_idx: 0
    mask: True
    padding_idx: 2
    encode_value: False
    max_text_length: *max_text_length

Loss:
  name: RobustScannerLoss
  # smoothing: True

Metric:
  name: RecMetric
  main_indicator: acc
  # is_filter: True

PostProcess:
  name: RobustScannerLabelDecode


Train:
  dataset:
    name: LMDBDataSet
    data_dir: ./
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RobustScannerLabelEncode: # Class handling label
      - RobustScannerRecResizeImg:
          image_shape: [3, 48, 48, 160]
          width_downsample_ratio: 0.25
          max_text_length: *max_text_length
      - KeepKeys:
          keep_keys: ['image', 'label', 'valid_ratio', 'word_positons'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ./
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RobustScannerLabelEncode: # Class handling label
      - RobustScannerRecResizeImg:
          image_shape: [3, 48, 48, 160]
          width_downsample_ratio: 0.25
          max_text_length: *max_text_length
      - KeepKeys:
          keep_keys: ['image', 'label', 'valid_ratio', 'word_positons'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 128
    num_workers: 1
    use_shared_memory: False
