Global:
  device: gpu
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/rec/u14m_filter/autostr_lstm_aster_tps_on
  eval_epoch_step: [0, 1]
  eval_batch_step: [0, 500]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  use_tensorboard: false
  infer_img:
  # for data or label process
  character_dict_path: ./tools/utils/EN_symbol_dict.txt
  max_text_length: 25
  use_space_char: False
  save_res_path: ./output/rec/u14m_filter/predicts_autostr_lstm_aster_tps_on.txt
  use_amp: True
  grad_clip_val: 1.0

Optimizer:
  name: Adam
  lr: 0.002 # for 4gpus bs256/gpu
  weight_decay: 0.0
  filter_bias_and_bn: False

LRScheduler:
  name: OneCycleLR
  warmup_epoch: 1.5 # pct_start 0.075*20 = 1.5ep
  cycle_momentum: False

Architecture:
  model_type: rec
  algorithm: autostr
  Transform:
    name: Aster_TPS
    tps_inputsize: [32, 64]
    tps_outputsize: [32, 128]
  Encoder:
    name: AutoSTREncoder
    stride_stages: '[(2, 2), (2, 1), (2, 2), (2, 1), (2, 1)]'
    conv_op_ids: [2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 4, 1, 1, 6, 6]
  Decoder:
    name: ASTERDecoder

Loss:
  name: ARLoss

Metric:
  name: RecMetric
  main_indicator: acc
  is_filter: True

PostProcess:
  name: ARLabelDecode

Train:
  dataset:
    name: LMDBDataSet
    data_dir: ../Union14M-L-LMDB-Filtered
    transforms:
      - DecodeImagePIL: # load image
          img_mode: RGB
      - PARSeqAugPIL:
      - ARLabelEncode: # Class handling label
      - RecTVResize:
          image_shape: [64, 256]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ../evaluation
    transforms:
      - DecodeImagePIL: # load image
          img_mode: RGB
      - ARLabelEncode: # Class handling label
      - RecTVResize:
          image_shape: [64, 256]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 2
