Global:
  device: gpu
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/rec/svtr_tiny_abinet_u14m/
  eval_epoch_step: [0, 1]
  eval_batch_step: [0, 500]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  use_tensorboard: false
  infer_img:
  # for data or label process
  character_dict_path: ./tools/utils/EN_symbol_dict.txt
  max_text_length: 25
  use_space_char: False
  save_res_path: ./output/rec/predicts_abinet.txt
  use_amp: True
  grad_clip_val: 20


Optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.0
  filter_bias_and_bn: False

LRScheduler:
  name: MultiStepLR
  milestones: [6]
  gamma: 0.1

Architecture:
  model_type: rec
  algorithm: ABINet
  Transform:
  Encoder:
    name: SVTRNet
    img_size: [32, 128]
    patch_merging: 'Conv'
    embed_dim: [64, 128, 256]
    depth: [3, 6, 3]
    num_heads: [2, 4, 8]
    mixer: ['Conv','Conv','Conv','Conv','Conv','Conv','FGlobal','Global','Global','Global','Global','Global']
    local_mixer: [[5, 5], [5, 5], [5, 5]]
    sub_k: [[1, 1], [1, 1]]
    feature2d: True
    last_stage: False
    prenorm: True
  Decoder:
    name: ABINetDecoder
    nhead: 4
    num_layers: 3
    dim_feedforward: 1024
    dropout: 0.1
    max_length: 25
    iter_size: 0

Loss:
  name: ABINetLoss

PostProcess:
  name: ABINetLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  is_filter: True

Train:
  dataset:
    name: LMDBDataSet
    data_dir: ../Union14M-LMDB-L-wh
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - PARSeqAug:
      - ABINetLabelEncode:
      - ABINetResize:
          image_shape: [3, 32, 128]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ../evaluation
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - ABINetLabelEncode:
      - ABINetResize:
          image_shape: [3, 32, 128]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 2
