Global:
  device: gpu
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  output_dir: ./output/rec/u14m_filter/resnet45_trans_matrn/
  eval_epoch_step: [0, 1]
  eval_batch_step: [0, 500]
  cal_metric_during_train: True
  pretrained_model:
  # ./openocr_nolang_abinet_lang.pth
  checkpoints:
  use_tensorboard: false
  infer_img:
  # for data or label process
  character_dict_path: ./tools/utils/EN_symbol_dict.txt
  max_text_length: 25
  use_space_char: False
  save_res_path: ./output/rec/u14m_filter/predicts_resnet45_trans_matrn.txt
  grad_clip_val: 20
  use_amp: True

Optimizer:
  name: Adam
  lr: 0.000133 # 4gpus 128bs/gpu
  weight_decay: 0.0
  filter_bias_and_bn: False

LRScheduler:
  name: MultiStepLR
  milestones: [12, 18]
  gamma: 0.1

Architecture:
  model_type: rec
  algorithm: MATRN
  Transform:
  Encoder:
    name: ResNet45
    in_channels: 3
    strides: [2, 1, 2, 1, 1]
  Decoder:
    name: MATRNDecoder
    iter_size: 3

Loss:
  name: ABINetLoss
  align_weight: 3.0

PostProcess:
  name: ABINetLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  is_filter: True

Train:
  dataset:
    name: LMDBDataSet
    data_dir: ../Union14M-L-LMDB-Filtered
    transforms:
      - DecodeImagePIL: # load image
          img_mode: RGB
      - PARSeqAugPIL:
      - ABINetLabelEncode:
      - RecTVResize:
          image_shape: [32, 128]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 128
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ../evaluation
    transforms:
      - DecodeImagePIL: # load image
          img_mode: RGB
      - ABINetLabelEncode:
      - RecTVResize:
          image_shape: [32, 128]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 2
